# Web server port
port: 11434

# SMTP configuration
smtp:
  host: smtp.example.com
  port: 587
  username: your-email@example.com
  authorization-code: "your-authorization-code"  # 建议使用环境变量
  from: your-email@example.com
  tls: true

# Verification code settings
verification-code:
  length: 6
  expiry: 300  # 5 minutes

# Allowed email suffixes
allowed-email-suffixes:
  - "@qq.com"
  - "@163.com"

# Messages
messages:
  success: "<h1 style='color:green'>Success! Player added.</h1>"
  invalid_code: "<h1 style='color:red'>Invalid code!</h1>"
  email_required: "<h1 style='color:red'>Email is required!</h1>"
  invalid_email: "<h1 style='color:red'>Invalid email format!</h1>"
  email_suffix_not_allowed: "<h1 style='color:red'>Email suffix not allowed! Allowed: {suffixes}</h1>"
  email_already_registered: "<h1 style='color:red'>This email is already registered!</h1>"
  console_success: "Added {player} to whitelist"
  console_error: "Error: {error}"
  index_title: "TR WhiteList Portal"
  username_label: "Minecraft Username"
  email_label: "Email Address"
  code_label: "Verification Code"
  submit_button: "Add to Whitelist"
#如果你是中国用户请把上面的message删除，将下面的_cn删掉
messages_cn:
  success: "<h1 style='color:green'>玩家添加成功!</h1>"
  invalid_code: "<h1 style='color:red'>错误的验证码!</h1>"
  email_required: "<h1 style='color:red'>错误的邮箱!</h1>"
  invalid_email: "<h1 style='color:red'>电子邮件格式无效!</h1>"
  email_suffix_not_allowed: "<h1 style='color:red'>不允许使用电子邮件后缀！允许： {suffixes}</h1>"
  email_already_registered: "<h1 style='color:red'>这个邮箱已经注册过了!</h1>"
  console_success: "已添加 {player} 到白名单"
  console_error: "错误的添加玩家 {player}: {error}"
  index_title: "白名单"
  username_label: "我的世界用户名"
  email_label: "邮箱地址"
  code_label: "验证码"
  submit_button: "启动!"
