name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Find JAR file
      id: find-jar
      run: |
        JAR_FILE=$(find . -path '*/target/*.jar' -not -name '*-sources.jar' -not -name '*-javadoc.jar' -not -name '*-tests.jar' | head -n 1)
        JAR_NAME=$(basename "$JAR_FILE")
        echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT
        echo "Found JAR: $JAR_NAME"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: ${{ steps.find-jar.outputs.jar_file }}
        retention-days: 7

    - name: Show artifact info
      run: |
        echo "JAR file has been uploaded as artifact"
        echo "After workflow completes, download from:"
        echo "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
